### ISSUE TITLE
Custom ColumnType not loading during rendering

### ISSUE THREAD

**Issue by ghost** [chafiq/TableBundle#9]
I've created a custom column type that I want to use to display boolean values.
I built it to extend IconType.

_config.yml_

```
emc_table:
    export:
    ...
    extensions:
        - MyBundle:Table\Column:boolean.html.twig
```

_MyBundle:Table\Column:boolean.html.twig_

```
{% block boolean_widget %}
    <i {{ block('attributes') }}></i>
{% endblock %}
```

_services.yml_

```
    table.column.boolean:
        class: MyBundle\Service\Table\Column\BooleanType
        tags:
            - { name: column.type, alias: boolean }
```

_BooleanType.php_

```
class BooleanType extends IconType
{
    /**
     * {@inheritdoc}
     */
    public function buildView(
        array &$view,
        ColumnInterface $column,
        array $data,
        array $options
    ) {
        parent::buildView($view, $column, $data, $options);

        $view['icon'] = $options['value'] ? $options['icon_true'] : $options['icon_false'];
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        parent::setDefaultOptions($resolver);

        $resolver->setDefaults([
            'icon_true'  => 'check',
            'icon_false' => 'ban'
        ]);

        $resolver->addAllowedTypes([
            'icon_true'  => 'string',
            'icon_false' => 'string',
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'boolean';
    }
}
```

The table renders just fine. Except in the column with the `boolean` type I get `<i></i>`. What am I missing?
